baseURL = "https://thecabbagebaggage.github.io/adritian"
languageCode = "en-us"
theme = "adritian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Experience"
  URL = "#experience"
  weight = 3

  [[menu.header]]
  name = "Blog"
  URL = "/blog"
  weight = 4

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 5


  [[menu.footer]]
  name = "ğŸ’â€â™‚ï¸ About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "ğŸ“š Publications"
  URL = "/publication"
  weight = 3

  [[menu.footer]]
  name = "ğŸ“¨ Contact"
  URL = "#contact"
  weight = 4


[params]

  sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager
  homepageExperienceCount = 6
  
  [params.logo]
    text1 = "Linus"
    text2 = "Kohl"

  [params.footer]
      copyright = "Â© Adritian. Free Hugo theme by AdriÃ¡n Moreno PeÃ±a."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"